//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQTTConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Device
    {
        public int Id { get; set; }
        public string Device_Id { get; set; }
        public string Application_Id { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool Status { get; set; }
    }
}
