//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQTTConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeviceConsumption
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string DeviceID { get; set; }
        public string Consumption { get; set; }
        public System.DateTime Created_ON { get; set; }
        public System.DateTime Updated_ON { get; set; }
    }
}
